/* capture.h - four-mic clap-triggered acoustic capture.
 *
 * This is user code, NOT generated by CubeMX. It lives outside the
 * USER CODE fences of main.c on purpose: CubeMX regeneration cannot touch
 * a file it does not own, so the capture logic is safe across regenerations.
 *
 * Usage from main.c:
 *   - call Capture_Arm() when the user asks for a recording (button press).
 *     It arms the array to listen for a clap; if a capture is already in
 *     progress the call is ignored.
 *   - call Capture_Poll() every pass of the main while(1) loop. It runs the
 *     recording state machine and, when a capture finishes, dumps all four
 *     channels over UART ("WAV4").
 *
 * The two HAL_DFSDM_FilterRegConv*Callback functions live in capture.c and
 * override the HAL weak defaults, so all DMA handling is contained here too.
 */
#ifndef CAPTURE_H
#define CAPTURE_H

void Capture_Arm(void);
void Capture_Poll(void);

#endif /* CAPTURE_H */
