/* loc_config.h - constants shared by the on-board localization pipeline.
 *
 * User code, NOT generated by CubeMX, so regeneration cannot touch it.
 *
 * Every number here has a counterpart in the Python reference. If you change
 * one, change the other, or the firmware stops being comparable to the
 * implementation it was validated against:
 *
 *   LOC_FS, LOC_C_SOUND        localization_sim.py  FS, C_SOUND
 *   LOC_WINDOW_BEFORE/AFTER    localize_capture.py  WINDOW_BEFORE/AFTER
 *   LOC_ONSET_FRACTION         find_clap() threshold, both Python scripts
 *
 * The whole point of the port is that on identical input it produces the same
 * numbers as localization_sim.py. Keep these aligned and that stays true.
 */
#ifndef LOC_CONFIG_H
#define LOC_CONFIG_H

/* Physics and sample rate. Must match the capture chain and the Python side. */
#define LOC_FS              16000.0f
#define LOC_C_SOUND         343.0f

/* Metres of path difference per sample of delay. Used all over the place, so
   it is named once here rather than open-coded as (C_SOUND / FS). */
#define LOC_METRES_PER_SAMPLE   (LOC_C_SOUND / LOC_FS)

#define LOC_NUM_MICS        4
/* Unique unordered pairs of 4 mics: (0,1)(0,2)(0,3)(1,2)(1,3)(2,3). */
#define LOC_NUM_PAIRS       6

/* Analysis window cut around the clap onset, in samples. Same split the
   Python scripts use: a little context before the onset, then the body of the
   transient. 256 + 1792 = 2048. */
#define LOC_WINDOW_BEFORE   256
#define LOC_WINDOW_AFTER    1792
#define LOC_WINDOW_LEN      (LOC_WINDOW_BEFORE + LOC_WINDOW_AFTER)

/* GCC-PHAT zero-pads to at least twice the window so the circular correlation
   cannot wrap a real peak around the end of the buffer. Python uses
   n = len(a) + len(b), which for equal-length windows is exactly 2x. Must be
   a power of two for the FFT. */
#define LOC_FFT_LEN         (2 * LOC_WINDOW_LEN)

/* Onset detector, mirroring find_clap() in the Python scripts: walk back from
   the envelope peak until the envelope drops to
   noise + LOC_ONSET_FRACTION * (peak - noise). */
#define LOC_ONSET_FRACTION  0.2f

/* Bins used to estimate the envelope median (the noise floor) without storing
   the whole 16000-sample envelope, which would not fit in RAM. See
   loc_median_estimate() in localize.c for why this is accurate enough. */
#define LOC_MEDIAN_BINS     2048

/* A capture whose peak-to-noise ratio is below this is reported as suspect.
   The Python scripts warn at the same level. Ratios are computed AFTER DC
   removal; before that fix a good clap read as 11.7 instead of 31.1. */
#define LOC_WEAK_SNR        14.7f

/* Condition number above which the array has blind directions worth warning
   about. Mirrors the POOR_CONES threshold in localize_capture.py. */
#define LOC_POOR_COND       2.0f

#endif /* LOC_CONFIG_H */
