/* capture.c - four-mic clap-triggered acoustic capture.
 *
 * User code, not generated by CubeMX (see capture.h). All the recording
 * state, buffers, DMA callbacks, and the UART dump live here so main.c stays
 * thin and the logic survives CubeMX regeneration untouched.
 *
 * The mics feed DFSDM filters 0-3, each filter drives a circular DMA into
 * its own dma_buf[m]. The filters are sync-started (see main.c section 2 and
 * Capture_Arm below), so all four DMAs run in lockstep and their half/full
 * interrupts arrive together. We exploit that: samples are only ever moved a
 * whole aligned "frame" at a time (the same half of all four channels), and
 * every channel is treated identically, so the stored channels stay
 * sample-aligned. That alignment is exactly what GCC-PHAT downstream needs.
 */
#include "main.h"
#include "capture.h"

/* --- capture configuration ------------------------------------------------ */
#define SAMPLE_RATE    16000
#define RECORD_SECS    1
#define NUM_MICS       4
#define TOTAL_SAMPLES  (SAMPLE_RATE * RECORD_SECS)
#define DMA_BUF_LEN    2048
/* Samples thrown away per capture before we start watching for the clap. The
   mics and the DFSDM filters both need a moment after start (turn-on pop, DC
   step). Running warm-up before we arm the trigger means the settling pop
   cannot be mistaken for a clap. 4000 samples = 0.25 s at 16 kHz. */
#define WARMUP_SAMPLES 4000
/* Sound-triggered capture level, in the same int16 domain the samples are
   stored in (i.e. after >>8). After warm-up, the first frame with any sample
   past this level is taken as the clap and becomes sample 0 of the stored
   second. This is what removes the need to time your clap: the array listens
   as long as it takes, then places the 1 s buffer on the clap. Room noise
   sits well under 1000 and a clap peaks near 15000, so 2500 has wide margin.
   Raise it if noise trips the trigger, lower it if a real clap never does. */
#define TRIGGER_LEVEL  2500

/* --- handles owned by the generated code (main.c and the BSP) ------------- */
extern DFSDM_Filter_HandleTypeDef hdfsdm1_filter0;
extern DFSDM_Filter_HandleTypeDef hdfsdm1_filter1;
extern DFSDM_Filter_HandleTypeDef hdfsdm1_filter2;
extern DFSDM_Filter_HandleTypeDef hdfsdm1_filter3;
extern UART_HandleTypeDef hcom_uart[];

/* --- capture state (file-private) ----------------------------------------- */
/* one DMA scratch buffer per mic; the DFSDM DMA fills these continuously */
static int32_t dma_buf[NUM_MICS][DMA_BUF_LEN];
/* the kept second per mic, int16 PCM ready to ship */
static int16_t recording[NUM_MICS][TOTAL_SAMPLES];
/* how many samples of the kept second each mic has banked so far */
static volatile uint32_t rec_index[NUM_MICS];
/* samples left to discard before the trigger arms; global because the four
   channels are drained in lockstep, so one counter keeps them identical */
static volatile uint32_t warmup_left = 0;
/* DMA half/full interrupt flags, one per mic */
static volatile uint8_t half_flag[NUM_MICS], full_flag[NUM_MICS];
/* 1 from arm until the kept second is dumped */
static volatile uint8_t recording_active = 0;
/* 0 while armed and listening for the clap, 1 once it has been heard */
static volatile uint8_t triggered = 0;
/* raised when a capture finishes and its dump is done; cleared by
   Capture_TakeResult so exactly one consumer acts on each recording */
static volatile uint8_t result_ready = 0;

/* Map the filter that raised an interrupt back to its mic index.
   filter0=ch2 PE7 rising -> mic0, filter1=ch1 PE7 falling -> mic1,
   filter2=ch0 PB1 rising -> mic2, filter3=ch3 PB1 falling -> mic3. */
static int filter_to_mic(DFSDM_Filter_HandleTypeDef *f)
{
    if (f == &hdfsdm1_filter0) return 0;
    if (f == &hdfsdm1_filter1) return 1;
    if (f == &hdfsdm1_filter2) return 2;
    return 3;
}

/* Bank one block of a mic's stream into its kept second, int16 (>>8), until
   that channel is full. */
static void store_samples(int mic, int32_t *src, uint32_t count)
{
    for (uint32_t i = 0; i < count && rec_index[mic] < TOTAL_SAMPLES; i++) {
        recording[mic][rec_index[mic]++] = (int16_t)(src[i] >> 8);
    }
}

/* True if any sample in this block is louder than TRIGGER_LEVEL, tested in
   the same int16 domain (>>8) the samples are stored in. This is what turns
   a clap into the start of a capture. */
static int block_exceeds(int32_t *src, uint32_t count)
{
    for (uint32_t i = 0; i < count; i++) {
        int32_t s = src[i] >> 8;
        if (s > TRIGGER_LEVEL || s < -TRIGGER_LEVEL) return 1;
    }
    return 0;
}

/* Handle one aligned frame: the same half (offset 0 or DMA_BUF_LEN/2) of all
   four channels, ready together because the filters are sync-started.
   Treating the four identically is what keeps rec_index equal across mics, so
   the stored channels stay sample-aligned no matter when the clap lands.
   Three phases:
     warm-up  - filter settling pop still draining, discard the frame.
     watching - warm-up done, not yet triggered. Discard unless the frame is
                loud on ANY channel (a clap), in which case latch triggered
                and fall through to store this frame as sample 0.
     storing  - bank every frame until each channel is full. */
static void process_frame(uint32_t offset)
{
    uint32_t count = DMA_BUF_LEN / 2;

    if (warmup_left > 0) {                       /* burn off settling pop */
        warmup_left = (warmup_left > count) ? (warmup_left - count) : 0;
        return;
    }

    if (!triggered) {                            /* listening for the clap */
        int loud = 0;
        for (int m = 0; m < NUM_MICS; m++)
            if (block_exceeds(&dma_buf[m][offset], count)) { loud = 1; break; }
        if (!loud) return;                       /* still quiet, drop frame */
        triggered = 1;                           /* clap: this frame is t=0 */
    }

    for (int m = 0; m < NUM_MICS; m++)           /* storing */
        store_samples(m, &dma_buf[m][offset], count);
}

/* Ship the four kept channels to the PC. Blue LED = "transmitting".
   Protocol: 8-byte header "WAV4" + little-endian uint32 of the per-channel
   byte count, then the four channels back to back in mic order. At
   RECORD_SECS=1 each channel is 32000 bytes, which fits one
   HAL_UART_Transmit (uint16_t size limit is 65535), so no chunking loop is
   needed. If RECORD_SECS ever grows, bring the chunking loop back. */
static void dump_capture(void)
{
    BSP_LED_On(LED_BLUE);
    uint32_t nbytes = TOTAL_SAMPLES * 2u;
    uint8_t header[8] = { 'W','A','V','4',
                          (uint8_t)nbytes, (uint8_t)(nbytes >> 8),
                          (uint8_t)(nbytes >> 16), (uint8_t)(nbytes >> 24) };
    HAL_UART_Transmit(&hcom_uart[COM1], header, 8, HAL_MAX_DELAY);
    for (int m = 0; m < NUM_MICS; m++)
        HAL_UART_Transmit(&hcom_uart[COM1], (uint8_t *)recording[m],
                          (uint16_t)nbytes, HAL_MAX_DELAY);
    BSP_LED_Off(LED_BLUE);
}

/* Arm the array to record. Ignored if a capture is already in progress, so a
   stray button press mid-capture does nothing. */
void Capture_Arm(void)
{
    if (recording_active) return;

    /* fresh start: rewind every mic and clear stale flags from any prior run */
    for (int m = 0; m < NUM_MICS; m++) {
        rec_index[m] = 0;
        half_flag[m] = 0;
        full_flag[m] = 0;
    }
    warmup_left = WARMUP_SAMPLES;     /* discard settling pop first */
    triggered = 0;                    /* then watch for the clap */
    result_ready = 0;                 /* previous result is now stale */
    recording_active = 1;

    BSP_LED_On(LED_GREEN);            /* armed: listening for a clap */

    /* Arm the whole hardware chain. Start the three sync-armed slave filters
       first; they wait. filter0 is started LAST and its start releases all
       four at the same instant, so the channels stay sample-aligned. From
       here on mic -> DFSDM -> DMA -> dma_buf runs with zero CPU involvement;
       circular DMA interrupts fire at each buffer's halfway point and end. */
    if (HAL_DFSDM_FilterRegularStart_DMA(&hdfsdm1_filter1, dma_buf[1], DMA_BUF_LEN) != HAL_OK) Error_Handler();
    if (HAL_DFSDM_FilterRegularStart_DMA(&hdfsdm1_filter2, dma_buf[2], DMA_BUF_LEN) != HAL_OK) Error_Handler();
    if (HAL_DFSDM_FilterRegularStart_DMA(&hdfsdm1_filter3, dma_buf[3], DMA_BUF_LEN) != HAL_OK) Error_Handler();
    if (HAL_DFSDM_FilterRegularStart_DMA(&hdfsdm1_filter0, dma_buf[0], DMA_BUF_LEN) != HAL_OK) Error_Handler();
}

/* Run the recording state machine. Call every main-loop pass. Does nothing
   until Capture_Arm() has been called. Because the filters are sync-started,
   the four half (and the four full) DMA interrupts arrive together, so we
   wait for the whole set before touching a frame and hand all four to
   process_frame at once. That lets the clap start the capture without ever
   breaking channel alignment: every mic stores exactly the same frames. */
void Capture_Poll(void)
{
    if (!recording_active) return;

    if (half_flag[0] && half_flag[1] && half_flag[2] && half_flag[3]) {
        for (int m = 0; m < NUM_MICS; m++) half_flag[m] = 0;
        /* First half stable; DMA is now writing the second half. */
        process_frame(0);
    }
    if (full_flag[0] && full_flag[1] && full_flag[2] && full_flag[3]) {
        for (int m = 0; m < NUM_MICS; m++) full_flag[m] = 0;
        /* Second half complete; DMA has wrapped to the first half. */
        process_frame(DMA_BUF_LEN / 2);
    }

    /* Done only once every mic has banked TOTAL_SAMPLES. */
    uint8_t all_done = 1;
    for (int m = 0; m < NUM_MICS; m++)
        if (rec_index[m] < TOTAL_SAMPLES) all_done = 0;

    if (all_done) {
        HAL_DFSDM_FilterRegularStop_DMA(&hdfsdm1_filter0);  /* silence the chain */
        HAL_DFSDM_FilterRegularStop_DMA(&hdfsdm1_filter1);
        HAL_DFSDM_FilterRegularStop_DMA(&hdfsdm1_filter2);
        HAL_DFSDM_FilterRegularStop_DMA(&hdfsdm1_filter3);
        recording_active = 0;            /* back to idle after this */
        BSP_LED_Off(LED_GREEN);
        dump_capture();
        /* Raised only after the dump, so the raw audio is already on the wire
           before any localization output follows it. catch_audio4.py stops
           reading at the end of the WAV4 payload, so the report that comes
           after cannot corrupt the capture it is describing. */
        result_ready = 1;
    }
}


int Capture_TakeResult(void)
{
    if (!result_ready) return 0;
    result_ready = 0;
    return 1;
}


const int16_t *Capture_Channel(int mic)
{
    if (mic < 0 || mic >= NUM_MICS) return 0;
    return recording[mic];
}


uint32_t Capture_Length(void)
{
    return TOTAL_SAMPLES;
}


int Capture_NumMics(void)
{
    return NUM_MICS;
}

/* DMA interrupt callbacks. These override the HAL weak defaults, so they must
   have external linkage (not static). Each maps the reporting filter back to
   its mic and raises the matching flag; the draining happens in Capture_Poll
   on the main loop, keeping the ISRs trivial. */
void HAL_DFSDM_FilterRegConvHalfCpltCallback(DFSDM_Filter_HandleTypeDef *f)
{
    half_flag[filter_to_mic(f)] = 1;
}

void HAL_DFSDM_FilterRegConvCpltCallback(DFSDM_Filter_HandleTypeDef *f)
{
    full_flag[filter_to_mic(f)] = 1;
}
